"""Compact final-writer contract for Hybrid Groq -> Gemini article generation.

Groq owns structured preprocessing/decision planning. Gemini owns only the Japanese
reader-facing article. This module is provider-free: it builds/validates the writer
surface but never imports Gemini, Groq, credentials, retry code or persistence.
"""
from __future__ import annotations

import json
import re

from content_generation_protocol import _human_editorial_style_rules, _source_fact_discipline
from groq_two_pass_article import validate_plan


class HybridWriterError(RuntimeError):
    pass


TITLE_MARKER = "===TITLE==="
ARTICLE_MARKER = "===ARTICLE==="
MAX_SOURCE_CONTEXT_CHARS = 14000
MIN_ARTICLE_CHARS = 1400
MAX_ARTICLE_CHARS = 2400
MIN_HEADINGS = 2
MAX_HEADINGS = 4
_FORBIDDEN_UNSUPPORTED_INTENSIFIERS = (
    "劇的", "驚異的", "革命的", "圧倒的", "完全に攻略", "完璧に機能",
)


def _bounded_context(text: str) -> str:
    value = str(text or "").strip()
    if not value:
        raise HybridWriterError("source_context_missing")
    return value[:MAX_SOURCE_CONTEXT_CHARS]


def build_gemini_writer_prompt(item: dict, plan: dict) -> str:
    """Build one compact Gemini writer prompt from a validated Groq Decision Plan.

    The plan is editorial/decision authority, not a license to invent facts. Source
    Context remains the factual ceiling. Management data is not regenerated by Gemini.
    """
    plan = validate_plan(dict(plan))
    source = str(item.get("source") or "Unknown").strip()
    name = str(item.get("name") or "").strip()
    url = str(item.get("url") or "").strip()
    if not name or not url:
        raise HybridWriterError("candidate_identity_missing")
    context = _bounded_context(item.get("source_context"))

    writer_plan = {
        "source_summary": plan["source_summary"],
        "what": plan["what"],
        "why_important": plan["why_important"],
        "decision": plan["decision"],
        "decision_reason": plan["decision_reason"],
        "decision_score": {
            "business_impact": plan["business_impact"],
            "technical_impact": plan["technical_impact"],
            "urgency": plan["urgency"],
            "market_impact": plan["market_impact"],
            "reliability": plan["reliability"],
            "total": plan["business_impact"] + plan["technical_impact"] + plan["urgency"] + plan["market_impact"] + plan["reliability"],
        },
        "action": plan["action"],
        "article_angle": plan["article_angle"],
        "reader_bridge": plan["reader_bridge"],
        "title_seed": plan["title_seed"],
        "access_status": plan["access_status"],
    }

    return f"""あなたはAI Intelligence Factoryの最終日本語Writerです。
この工程では記事タイトルと本文だけを担当します。採点・分類・Decision Planは前工程で確定済みです。
管理データを再計算・再生成してはいけません。

【最優先：Factを増やさない】
- 事実の上限はSOURCE CONTEXT。PLANは編集方針と判断であり、新しい事実ソースではない。
- SOURCE CONTEXTにない固有名詞、数値、価格、アクセス条件、機能、比較、因果、効果を追加しない。
- SOURCE CONTEXTの語を説明するために、モデル知識から別の技術事実を足さない。
- PLANのDecision/Action/Scoreより強い推奨へ書き換えない。
- access_status=NOT_CONFIRMEDなら、「誰でも使えない」「限定提供である」「一般公開されない」も断定しない。確認できるのは一般利用条件が未確認ということだけ。
- Daybreak Blue等の評価条件から「安全装置を外した」「制限を緩めた」「専門家向け」等の具体像を作らない。
- 安全策はSOURCE CONTEXTにある名称・存在以上の機能を説明しない。「常時判定」「ログ収集」「AIの意図を読む」「完全に防ぐ」等を足さない。
- 「劇的」「驚異的」「革命的」「圧倒的」「完全に攻略」等、Evidenceより強い形容を使わない。面白さは形容詞ではなく確認済み事実で出す。

【読者体験：非エンジニアを置いていかない】
- 中学生〜非エンジニアでも「要するに何が起きたか」を一文で言える日本語にする。
- 最初の600字は特に平易にし、未説明の専門語を一文に2個以上積まない。
- 本文で読者が覚える専門概念は原則2〜3個に絞る。Decisionに不要な英語名・内部名称・安全策の列挙は圧縮する。
- 英語の正式名を出すときは、先に普通の日本語で役割を説明する。日本語だけで十分なら英語を併記しない。
- 比喩は最大1つ。SOURCE CONTEXTにない装置・人物・運用条件を比喩の事実のように持ち込まない。似ている点だけを短く使う。
- 発表要約から始めず、確認済みの意外な事実を入口にする。ただし煽らない。
- 読者への近さは雑談の追加ではなく、硬い説明を普通の言葉へ置き換えて作る。
- 最後は「私なら」で始まる1段落で、PLANのDecision/Actionと同じ距離感の判断に着地する。

【構造契約】
- 箇条書き・番号リストは禁止。本文は自然な段落だけで書く。
- Markdown見出しを必ず{MIN_HEADINGS}〜{MAX_HEADINGS}個使う。見出し行は必ず「## 見出し」の形式。裸の見出しは禁止。
- 見出しは記事固有の日本語にし、「なぜ重要」「まとめ」「最終判断」のような汎用ラベルだけにしない。
- タイトルは「。」「？」のどちらかで終える。
- 本文は{MIN_ARTICLE_CHARS}〜{MAX_ARTICLE_CHARS}日本語文字を目安にする。水増ししない。
- 同じ事実を専門説明と比喩説明で二重に説明しない。

{_source_fact_discipline(source)}
{_human_editorial_style_rules()}

【対象】
Source: {source}
Name: {name}
Primary URL: {url}

【SOURCE CONTEXT — factual ceiling】
{context}

【GROQ DECISION PLAN — editorial/decision authority, not factual evidence】
{json.dumps(writer_plan, ensure_ascii=False, indent=2)}

【最終セルフチェック】
返答前にARTICLEだけを読み、次を満たさない箇所は新情報を足さず削除・圧縮・言い換えで直す。
1. SOURCE CONTEXTにない機能・因果・アクセス条件を作っていない。
2. 「劇的」「驚異的」などEvidenceより強い語がない。
3. 未説明の専門語が連続していない。
4. Markdownの「## 」見出しが{MIN_HEADINGS}〜{MAX_HEADINGS}個ある。
5. 最後がPLANと矛盾しない「私なら」の判断になっている。

【出力】
次の2ブロックだけを返す。説明・管理データ・コードフェンスは禁止。
{TITLE_MARKER}
記事タイトル（#なし。「。」または「？」で終える）
{ARTICLE_MARKER}
記事本文（Markdownの##見出しを必ず含める）
"""


def parse_gemini_writer_output(text: str) -> tuple[str, str]:
    value = str(text or "")
    match = re.fullmatch(
        rf"\s*{re.escape(TITLE_MARKER)}\s*\n(.+?)\n{re.escape(ARTICLE_MARKER)}\s*\n(.+?)\s*",
        value,
        re.S,
    )
    if not match:
        raise HybridWriterError("writer_output_format_invalid")
    title = match.group(1).strip()
    article = match.group(2).strip()
    if not title.endswith(("。", "？")):
        raise HybridWriterError("writer_title_punctuation_invalid")
    if re.search(r"(?m)^\s*(?:[-*+]\s+|\d+[.)]\s+)", article):
        raise HybridWriterError("writer_list_output_forbidden")
    headings = re.findall(r"(?m)^##\s+\S.+$", article)
    if not MIN_HEADINGS <= len(headings) <= MAX_HEADINGS:
        raise HybridWriterError("writer_markdown_heading_contract_invalid")
    if any(term in article for term in _FORBIDDEN_UNSUPPORTED_INTENSIFIERS):
        raise HybridWriterError("writer_unsupported_intensifier")
    if len(article) < MIN_ARTICLE_CHARS:
        raise HybridWriterError("writer_article_too_short")
    if len(article) > MAX_ARTICLE_CHARS + 500:
        raise HybridWriterError("writer_article_excessive")
    if not article.rstrip().endswith(("。", "！", "？")):
        raise HybridWriterError("writer_article_incomplete")
    last_paragraph = next((p.strip() for p in reversed(re.split(r"\n\s*\n", article)) if p.strip()), "")
    if not last_paragraph.startswith("私なら"):
        raise HybridWriterError("writer_decision_voice_missing")
    return title, article


def deterministic_management_data(plan: dict) -> dict:
    """Return management data without a second Gemini interpretation."""
    plan = validate_plan(dict(plan))
    total = sum(plan[key] for key in (
        "business_impact", "technical_impact", "urgency", "market_impact", "reliability"
    ))
    return {
        "source_summary": plan["source_summary"],
        "what": plan["what"],
        "why_important": plan["why_important"],
        "decision": plan["decision"],
        "decision_reason": list(plan["decision_reason"]),
        "decision_score": {
            "business_impact": plan["business_impact"],
            "technical_impact": plan["technical_impact"],
            "urgency": plan["urgency"],
            "market_impact": plan["market_impact"],
            "reliability": plan["reliability"],
            "total": total,
        },
        "action": plan["action"],
        "article_value": plan["article_value"],
        "access_status": plan["access_status"],
    }
