"""Compact final-writer contract for Hybrid Groq -> Gemini article generation.

Groq owns structured preprocessing/decision planning. Gemini owns only the Japanese
reader-facing article. This module is provider-free: it builds/validates the writer
surface but never imports Gemini, Groq, credentials, retry code or persistence.
"""
from __future__ import annotations

import json
import re

from content_generation_protocol import _human_editorial_style_rules, _source_fact_discipline
from groq_two_pass_article import validate_plan


class HybridWriterError(RuntimeError):
    pass


TITLE_MARKER = "===TITLE==="
ARTICLE_MARKER = "===ARTICLE==="
MAX_SOURCE_CONTEXT_CHARS = 14000
MIN_ARTICLE_CHARS = 1200
MAX_ARTICLE_CHARS = 3000


def _bounded_context(text: str) -> str:
    value = str(text or "").strip()
    if not value:
        raise HybridWriterError("source_context_missing")
    return value[:MAX_SOURCE_CONTEXT_CHARS]


def build_gemini_writer_prompt(item: dict, plan: dict) -> str:
    """Build one compact Gemini writer prompt from a validated Groq Decision Plan.

    The plan is editorial/decision authority, not a license to invent facts. Source
    Context remains the factual ceiling. Management data is not regenerated by Gemini.
    """
    plan = validate_plan(dict(plan))
    source = str(item.get("source") or "Unknown").strip()
    name = str(item.get("name") or "").strip()
    url = str(item.get("url") or "").strip()
    if not name or not url:
        raise HybridWriterError("candidate_identity_missing")
    context = _bounded_context(item.get("source_context"))

    # Keep only fields required to write the article. Exact scores are included so prose
    # cannot accidentally imply a stronger decision than the deterministic management block.
    writer_plan = {
        "source_summary": plan["source_summary"],
        "what": plan["what"],
        "why_important": plan["why_important"],
        "decision": plan["decision"],
        "decision_reason": plan["decision_reason"],
        "decision_score": {
            "business_impact": plan["business_impact"],
            "technical_impact": plan["technical_impact"],
            "urgency": plan["urgency"],
            "market_impact": plan["market_impact"],
            "reliability": plan["reliability"],
            "total": plan["business_impact"] + plan["technical_impact"] + plan["urgency"] + plan["market_impact"] + plan["reliability"],
        },
        "action": plan["action"],
        "article_angle": plan["article_angle"],
        "reader_bridge": plan["reader_bridge"],
        "title_seed": plan["title_seed"],
        "access_status": plan["access_status"],
    }

    return f"""あなたはAI Intelligence Factoryの最終日本語Writerです。
この工程では記事本文だけを担当します。採点・分類・Decision Planは前工程で確定済みです。
管理データを再計算・再生成してはいけません。

【絶対境界】
- 事実の上限はSOURCE CONTEXT。PLANは編集方針と判断であり、新しい事実ソースではない。
- SOURCE CONTEXTにない固有名詞、数値、価格、アクセス条件、機能、比較、因果、効果を追加しない。
- PLANのDecision/Action/Scoreより強い推奨へ書き換えない。
- access_status=NOT_CONFIRMEDなら、利用可能・一般提供・申請可能・PoC可能と推測しない。
- 安全策の名称から機能や効果を推測しない。
- 不足する説明をモデル知識で埋めない。必要なら「一次情報からはここまで」と自然に限定する。

【読者体験】
- 中学生〜非エンジニアでも入口から理解でき、専門家にも判断材料が残る日本語にする。
- 発表要約から始めず、SOURCE CONTEXTにある最も意外な事実・変化・困りごとのどれか1つから入る。
- 専門語は必要になった時点で普通の言葉に言い換える。
- AI的な定型句、均一な段落、機械的な箇条書きを避ける。
- 箇条書き・番号リストは禁止。本文は自然な段落で書く。
- 見出しは2〜4個。記事固有の日本語にする。
- 最後は「私なら」に相当する人間の判断で閉じる。ただし架空の体験は作らない。
- 本文は{MIN_ARTICLE_CHARS}〜{MAX_ARTICLE_CHARS}日本語文字を目安にする。根拠不足なら水増ししない。

{_source_fact_discipline(source)}
{_human_editorial_style_rules()}

【対象】
Source: {source}
Name: {name}
Primary URL: {url}

【SOURCE CONTEXT — factual ceiling】
{context}

【GROQ DECISION PLAN — editorial/decision authority, not factual evidence】
{json.dumps(writer_plan, ensure_ascii=False, indent=2)}

【出力】
次の2ブロックだけを返す。説明・管理データ・コードフェンスは禁止。
{TITLE_MARKER}
記事タイトル（#なし。「。」または「？」で終える）
{ARTICLE_MARKER}
記事本文
"""


def parse_gemini_writer_output(text: str) -> tuple[str, str]:
    value = str(text or "")
    match = re.fullmatch(
        rf"\s*{re.escape(TITLE_MARKER)}\s*\n(.+?)\n{re.escape(ARTICLE_MARKER)}\s*\n(.+?)\s*",
        value,
        re.S,
    )
    if not match:
        raise HybridWriterError("writer_output_format_invalid")
    title = match.group(1).strip()
    article = match.group(2).strip()
    if not title.endswith(("。", "？")):
        raise HybridWriterError("writer_title_punctuation_invalid")
    if re.search(r"(?m)^\s*(?:[-*+]\s+|\d+[.)]\s+)", article):
        raise HybridWriterError("writer_list_output_forbidden")
    if len(article) < MIN_ARTICLE_CHARS:
        raise HybridWriterError("writer_article_too_short")
    if len(article) > MAX_ARTICLE_CHARS + 800:
        raise HybridWriterError("writer_article_excessive")
    if not article.rstrip().endswith(("。", "！", "？")):
        raise HybridWriterError("writer_article_incomplete")
    return title, article


def deterministic_management_data(plan: dict) -> dict:
    """Return management data without a second Gemini interpretation."""
    plan = validate_plan(dict(plan))
    total = sum(plan[key] for key in (
        "business_impact", "technical_impact", "urgency", "market_impact", "reliability"
    ))
    return {
        "source_summary": plan["source_summary"],
        "what": plan["what"],
        "why_important": plan["why_important"],
        "decision": plan["decision"],
        "decision_reason": list(plan["decision_reason"]),
        "decision_score": {
            "business_impact": plan["business_impact"],
            "technical_impact": plan["technical_impact"],
            "urgency": plan["urgency"],
            "market_impact": plan["market_impact"],
            "reliability": plan["reliability"],
            "total": total,
        },
        "action": plan["action"],
        "article_value": plan["article_value"],
        "access_status": plan["access_status"],
    }
