"""Current public-note publication contract for AI Intelligence Factory.

The contract is intentionally explicit and deterministic.  A Content Intelligence row may
remain historically marked Ready after the production quality/format stack evolves, so the
Ready status alone is not sufficient evidence that its persisted manuscript/eyecatch was
produced under the current policy.

A current Ready manuscript is stamped in its Notion code-block caption.  note Ready sync and
note draft creation both require the exact current stamp.  Older/unversioned Ready manuscripts
remain available for audit but are fail-closed for publication until they are regenerated by
the current production pipeline.
"""
from __future__ import annotations

CONTRACT_ID = "run194-current-publication-contract-v1"
PRODUCTION_STACK = "run172-run183"
ARTICLE_QUALITY_POLICY = "run175-run176+reader-value-review"
EYECATCH_POLICY = "run178-run183"

LEGACY_READY_CAPTION = "AIIF_MANUSCRIPT:READY"
READY_CAPTION_PREFIX = "AIIF_MANUSCRIPT:READY|"
CURRENT_READY_CAPTION = (
    f"{READY_CAPTION_PREFIX}contract={CONTRACT_ID}"
    f"|production={PRODUCTION_STACK}"
    f"|quality={ARTICLE_QUALITY_POLICY}"
    f"|eyecatch={EYECATCH_POLICY}"
)


def is_current_ready_caption(value: str) -> bool:
    return str(value or "").strip() == CURRENT_READY_CAPTION


def is_ready_family_caption(value: str) -> bool:
    text = str(value or "").strip()
    return text == LEGACY_READY_CAPTION or text.startswith(READY_CAPTION_PREFIX)
