"""Run280 fail-closed guard for Publication Contract dependency completeness.

Stage4 made ``runtime_layers.py`` the runtime-order authority. Stage5 ensures that every
active code surface capable of changing a persisted public article is represented in the
content-addressed Publication Contract, and that every policy file triggers Note Ready queue
reconciliation on main.

Selection-only, member-only, recovery-only, quota/retry, synthetic, obsolete compatibility,
and observational modules are explicitly exempt so operational changes do not invalidate all
Ready manuscripts.
"""
from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

REQUIRED_PUBLICATION_DEPENDENCIES = (
    "runtime_layers.py",
    "source_normalization.py",
    "evidence_context.py",
    "reader_experience_signals.py",
    "editorial_naturalness.py",
    "note_manuscript.py",
    "gate_reasoning.py",
    "screening_protocol.py",
    "notion_payloads.py",
    "source_document_parsing.py",
    "content_generation_protocol.py",
    "evidence_sufficiency.py",
    "fact_validation_signals.py",
    "source_boundary_validation.py",
    "business_source_acquisition.py",
    "run269_acquisition_precision.py",
    "run269_vendor_current_state.py",
    "reader_quality_precision.py",
    "run260_gemini_model_routing.py",
    "run268_business_source_strategy.py",
    "run269_business_source_precision.py",
)

# These are intentionally outside the policy fingerprint. Reasons are narrow and auditable:
# they can change which work runs, when it runs, or what member/telemetry/synthetic surface is
# updated, but they do not define the persisted public manuscript/eyecatch bytes or gates.
EXPLICIT_NON_PUBLICATION_DEPENDENCIES = {
    "product_delivery_maintenance.py": "member/product maintenance only",
    "deep_dive_portfolio.py": "candidate selection only",
    "candidate_identity.py": "dedupe/entity selection only",
    "source_roi_policy.py": "source allocation/learning only",
    "deferred_queue_policy.py": "queue scheduling only",
    "product_review_protocol.py": "paid decision-product review only",
    "article_revalidation.py": "bounded recovery/controller only; canonical pipeline owns regenerated bytes",
    "run231_performance_telemetry.py": "observational telemetry only",
    "run203_runtime_state_channel.py": "operational runtime-state channel only",
    "gemini_timeout_rpd_fail_closed.py": "quota reservation/timeout safety only",
    "gemini_transient_recovery.py": "transport retry/failover safety only",
    "regression_suite.py": "synthetic regression entrypoint only",
    "legacy_eyecatch_renderer.py": "obsolete compatibility bridge; current editorial renderer is separately fingerprinted",
}

CLASSIFICATION_SURFACES = (
    "pipeline.py",
    "production_pipeline.py",
    "runtime_layers.py",
)

# Current source overlays delegate real acquisition logic to these files. Their local imports
# must also be policy-covered; otherwise changing a helper could bypass the policy SHA.
TRANSITIVE_MATERIAL_SURFACES = (
    "run268_business_source_strategy.py",
    "run269_business_source_precision.py",
    "run269_vendor_current_state.py",
    "run269_acquisition_precision.py",
)


def _read_ast(path: Path) -> ast.AST:
    try:
        return ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, SyntaxError) as exc:
        raise RuntimeError(f"cannot parse {path.name}: {exc}") from exc


def _literal_string_sequence(root: Path, path: str, name: str) -> tuple[str, ...]:
    tree = _read_ast(root / path)
    for node in getattr(tree, "body", []):
        target_name = None
        value = None
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            target_name, value = node.targets[0].id, node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            target_name, value = node.target.id, node.value
        if target_name != name or not isinstance(value, (ast.Tuple, ast.List)):
            continue
        items: list[str] = []
        for element in value.elts:
            if not isinstance(element, ast.Constant) or not isinstance(element.value, str):
                raise RuntimeError(f"{path}:{name} must contain literal strings only")
            items.append(element.value)
        return tuple(items)
    raise RuntimeError(f"{path}:{name} literal sequence not found")


def _local_import_files(root: Path, relative: str) -> set[str]:
    path = root / relative
    tree = _read_ast(path)
    modules: set[str] = set()
    for node in ast.walk(tree):
        names: list[str] = []
        if isinstance(node, ast.Import):
            names.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            names.append(node.module)
        for module in names:
            top = module.split(".", 1)[0]
            candidate = f"{top}.py"
            if (root / candidate).is_file():
                modules.add(candidate)
    return modules


def _workflow_tracked_paths(root: Path) -> set[str]:
    workflow = root / ".github/workflows/note-ready-sync.yml"
    text = workflow.read_text(encoding="utf-8")
    return set(re.findall(r"^\s*-\s*['\"]([^'\"]+)['\"]\s*$", text, flags=re.MULTILINE))


def validate_repository(root: Path = ROOT) -> list[str]:
    failures: list[str] = []
    required_files = {
        "publication_contract.py",
        ".github/workflows/note-ready-sync.yml",
        *CLASSIFICATION_SURFACES,
        *TRANSITIVE_MATERIAL_SURFACES,
    }
    for relative in sorted(required_files):
        if not (root / relative).is_file():
            failures.append(f"required Stage5 surface missing: {relative}")
    if failures:
        return failures

    try:
        policy = _literal_string_sequence(root, "publication_contract.py", "PUBLICATION_POLICY_FILES")
    except RuntimeError as exc:
        return [str(exc)]

    policy_set = set(policy)
    if len(policy_set) != len(policy):
        failures.append("PUBLICATION_POLICY_FILES contains duplicate entries")

    for relative in policy:
        if not (root / relative).is_file():
            failures.append(f"publication policy file does not exist: {relative}")

    for relative in REQUIRED_PUBLICATION_DEPENDENCIES:
        if relative not in policy_set:
            failures.append(f"publication-material dependency missing from policy fingerprint: {relative}")

    classified = policy_set | set(EXPLICIT_NON_PUBLICATION_DEPENDENCIES)
    for surface in (*CLASSIFICATION_SURFACES, *TRANSITIVE_MATERIAL_SURFACES):
        try:
            dependencies = _local_import_files(root, surface)
        except RuntimeError as exc:
            failures.append(str(exc))
            continue
        for dependency in sorted(dependencies):
            if dependency == surface:
                continue
            if dependency not in classified:
                failures.append(
                    f"unclassified local dependency from {surface}: {dependency}; "
                    "add it to PUBLICATION_POLICY_FILES or document a narrow operational exemption"
                )

    try:
        tracked = _workflow_tracked_paths(root)
    except OSError as exc:
        failures.append(f"cannot read note-ready-sync workflow: {exc}")
        tracked = set()
    for relative in policy:
        if relative not in tracked:
            failures.append(f"policy file does not trigger Note Ready reconciliation: {relative}")

    return failures


def main() -> int:
    failures = validate_repository(ROOT)
    if failures:
        print("Run280 Publication Dependency Completeness: FAIL")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print("Run280 Publication Dependency Completeness: PASS")
    print(f"- required publication dependencies: {len(REQUIRED_PUBLICATION_DEPENDENCIES)}")
    print("- active local dependencies: policy-covered or explicitly operational")
    print("- Note Ready reconciliation paths: synchronized")
    return 0


if __name__ == "__main__":
    sys.exit(main())
