"""Fail-closed guard for Publication Contract dependency completeness.

Run280 introduced dependency classification. Run281 strengthens it from selected-surface
checking to full recursive closure: every local import of every fingerprinted policy module
must itself be fingerprinted or carry a narrow documented non-publication exemption.

Operational policy is explicit-only: publication policy changes must never auto-run a live
Note Ready reconciliation from push. Instead, every authorized Daily ONE-SHOT must explicitly
dispatch Note Ready reconciliation after the production run.
"""
from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

REQUIRED_PUBLICATION_DEPENDENCIES = (
    "runtime_layers.py",
    "source_normalization.py",
    "evidence_context.py",
    "reader_experience_signals.py",
    "editorial_naturalness.py",
    "candidate_identity.py",
    "note_manuscript.py",
    "publication_source_contract.py",
    "gate_reasoning.py",
    "screening_protocol.py",
    "notion_payloads.py",
    "source_document_parsing.py",
    "content_generation_protocol.py",
    "evidence_sufficiency.py",
    "fact_validation_signals.py",
    "source_boundary_validation.py",
    "business_source_acquisition.py",
    "run269_acquisition_precision.py",
    "run269_vendor_current_state.py",
    "reader_quality_precision.py",
    "run260_gemini_model_routing.py",
    "run268_business_source_strategy.py",
    "run269_business_source_precision.py",
)

# Narrow exemptions only. Any newly imported local module is untrusted by default.
EXPLICIT_NON_PUBLICATION_DEPENDENCIES = {
    "pending_retry_validation.py": "bounded nonpersistent validation controller; canonical Production generation owns quality gates and bytes",
    "gemini_temporary_exclusion.py": "expiry-bound provider admission only; no public-byte or quality-gate policy",
    "ready_rescue_validation.py": "bounded ONE-SHOT orchestration only; canonical generation owns gates and persistence",
    "production_e2e_validation.py": "bounded single-article E2E orchestration/preflight only; canonical pipeline owns public bytes, gates, persistence, and note publication contract",
    "local_skills_daily_canary.py": "bounded nonpersistent fresh-record validation controller; persist_results=False is mandatory, downstream publication fan-out is forbidden, and no Ready/public bytes can be persisted",
    "stale_ready_batch_revalidation.py": "bounded ONE-SHOT stale Ready controller only; canonical generate_intelligence_report owns public bytes, gates, and persistence",
    "product_delivery_maintenance.py": "member/product maintenance only",
    "deep_dive_portfolio.py": "candidate selection only",
    "source_roi_policy.py": "source allocation/learning only",
    "deferred_queue_policy.py": "queue scheduling only",
    "product_review_protocol.py": "paid decision-product review only",
    "article_revalidation.py": "bounded recovery/controller only; canonical pipeline owns regenerated bytes",
    "run231_performance_telemetry.py": "observational telemetry only",
    "run203_runtime_state_channel.py": "operational runtime-state channel only",
    "gemini_timeout_rpd_fail_closed.py": "quota reservation/timeout safety only",
    "gemini_transient_recovery.py": "transport retry/failover safety only",
    "gemini_provider_resilience.py": "provider transport classification/retry/circuit safety only; no public-byte or gate policy",
    "run346_backlog_budget_reserve.py": "full-run Deep Dive budget partition/scheduling only; no public-byte, gate, model-routing, retry, or Notion policy",
    "run367_x_daily_discovery.py": "additive candidate acquisition only; raw X is discovery-only and canonical pipeline owns generated/public bytes",
    "regression_suite.py": "synthetic regression entrypoint only",
    "legacy_eyecatch_renderer.py": "obsolete compatibility bridge; current editorial renderer is separately fingerprinted",
}

# Backward-compatible names retained for the Run280 adversarial fixture API. Run281 no longer
# limits scanning to these lists; validate_repository audits every policy module instead.
CLASSIFICATION_SURFACES: tuple[str, ...] = ()
TRANSITIVE_MATERIAL_SURFACES: tuple[str, ...] = ()


def _read_ast(path: Path) -> ast.AST:
    try:
        return ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, SyntaxError) as exc:
        raise RuntimeError(f"cannot parse {path.name}: {exc}") from exc


def _literal_string_sequence(root: Path, path: str, name: str) -> tuple[str, ...]:
    tree = _read_ast(root / path)
    for node in getattr(tree, "body", []):
        target_name = None
        value = None
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            target_name, value = node.targets[0].id, node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            target_name, value = node.target.id, node.value
        if target_name != name or not isinstance(value, (ast.Tuple, ast.List)):
            continue
        items: list[str] = []
        for element in value.elts:
            if not isinstance(element, ast.Constant) or not isinstance(element.value, str):
                raise RuntimeError(f"{path}:{name} must contain literal strings only")
            items.append(element.value)
        return tuple(items)
    raise RuntimeError(f"{path}:{name} literal sequence not found")


def _local_import_files(root: Path, relative: str) -> set[str]:
    tree = _read_ast(root / relative)
    modules: set[str] = set()
    for node in ast.walk(tree):
        names: list[str] = []
        if isinstance(node, ast.Import):
            names.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            names.append(node.module)
        for module in names:
            top = module.split(".", 1)[0]
            candidate = f"{top}.py"
            if (root / candidate).is_file():
                modules.add(candidate)
    return modules


def _workflow_trigger_keys(text: str) -> set[str]:
    triggers: set[str] = set()
    in_on = False
    for line in text.splitlines():
        if not in_on:
            if line == "on:":
                in_on = True
            continue
        if line and not line.startswith(" "):
            break
        match = re.match(r"^  ([A-Za-z_]+):", line)
        if match:
            triggers.add(match.group(1))
    return triggers


def _one_shot_dispatches_note_ready(root: Path) -> bool:
    workflow = root / ".github/workflows/daily-one-shot.yml"
    text = workflow.read_text(encoding="utf-8")
    return re.search(r"\bgh\s+workflow\s+run\s+note-ready-sync\.yml\b", text) is not None


def validate_repository(root: Path = ROOT) -> list[str]:
    failures: list[str] = []
    for relative in (
        "publication_contract.py",
        ".github/workflows/note-ready-sync.yml",
        ".github/workflows/daily-one-shot.yml",
    ):
        if not (root / relative).is_file():
            failures.append(f"required publication surface missing: {relative}")
    if failures:
        return failures

    try:
        policy = _literal_string_sequence(root, "publication_contract.py", "PUBLICATION_POLICY_FILES")
    except RuntimeError as exc:
        return [str(exc)]

    policy_set = set(policy)
    if len(policy_set) != len(policy):
        failures.append("PUBLICATION_POLICY_FILES contains duplicate entries")

    for relative in policy:
        if not (root / relative).is_file():
            failures.append(f"publication policy file does not exist: {relative}")

    for relative in REQUIRED_PUBLICATION_DEPENDENCIES:
        if relative not in policy_set:
            failures.append(f"publication-material dependency missing from policy fingerprint: {relative}")

    classified = policy_set | set(EXPLICIT_NON_PUBLICATION_DEPENDENCIES)
    for surface in policy:
        if not (root / surface).is_file():
            continue
        try:
            dependencies = _local_import_files(root, surface)
        except RuntimeError as exc:
            failures.append(str(exc))
            continue
        for dependency in sorted(dependencies):
            if dependency == surface:
                continue
            if dependency not in classified:
                failures.append(
                    f"unclassified local dependency from {surface}: {dependency}; "
                    "fingerprint it or document a narrow non-publication exemption"
                )

    try:
        note_ready_text = (root / ".github/workflows/note-ready-sync.yml").read_text(encoding="utf-8")
        note_ready_triggers = _workflow_trigger_keys(note_ready_text)
    except OSError as exc:
        failures.append(f"cannot read note-ready-sync workflow: {exc}")
        note_ready_triggers = set()

    forbidden = sorted(note_ready_triggers & {"push", "schedule"})
    if forbidden:
        failures.append(
            "Note Ready reconciliation must not auto-run from "
            + ", ".join(forbidden)
            + "; use explicit ONE-SHOT/manual dispatch"
        )

    try:
        if not _one_shot_dispatches_note_ready(root):
            failures.append("Daily ONE-SHOT does not explicitly dispatch Note Ready reconciliation")
    except OSError as exc:
        failures.append(f"cannot read daily-one-shot workflow: {exc}")

    return failures


def main() -> int:
    failures = validate_repository(ROOT)
    if failures:
        print("Publication Dependency Completeness: FAIL")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print("Publication Dependency Completeness: PASS")
    print(f"- fingerprinted policy files: {len(_literal_string_sequence(ROOT, 'publication_contract.py', 'PUBLICATION_POLICY_FILES'))}")
    print("- every fingerprinted module local import: classified")
    print("- Note Ready reconciliation: explicit ONE-SHOT dispatch only")
    return 0


if __name__ == "__main__":
    sys.exit(main())
