#!/usr/bin/env python3
"""Aggregate privacy-safe Free note -> subscription metrics.

This utility deliberately does not fetch subscriber/member identities. It joins aggregate metrics
with Ready-article attribution manifests generated by pipeline.py. No output from this script is fed
back into production ranking yet; that is a separate, future feedback-loop step after enough data exists.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
from collections import defaultdict
from pathlib import Path

ALLOWED_METRIC_COLUMNS = {
    "article_id", "attribution_method", "note_url", "period_start", "period_end",
    "note_views", "cta_clicks", "new_subscribers", "retained_subscribers",
    "subscription_revenue_yen",
}
REQUIRED_COLUMNS = {"article_id", "attribution_method"}
NUMERIC_COLUMNS = {
    "note_views", "cta_clicks", "new_subscribers", "retained_subscribers",
    "subscription_revenue_yen",
}
FORBIDDEN_PII_HINTS = {
    "email", "mail", "name", "member_id", "user_id", "customer_id",
    "payment_id", "phone", "address", "account_id",
}

ATTRIBUTION_METHODS = {"note_dashboard_only", "tracked_cta", "end_to_end", "manual_verified"}
METHOD_ALLOWED_METRICS = {
    "note_dashboard_only": {"note_views"},
    "tracked_cta": {"note_views", "cta_clicks"},
    "end_to_end": set(NUMERIC_COLUMNS),
    "manual_verified": set(NUMERIC_COLUMNS),
}


def _optional_number(value: str, field: str):
    text = (value or "").strip()
    if not text:
        return None
    try:
        number = float(text)
    except ValueError as exc:
        raise ValueError(f"{field} must be numeric or blank: {text!r}") from exc
    if not math.isfinite(number) or number < 0:
        raise ValueError(f"{field} must be a finite non-negative number")
    if field != "subscription_revenue_yen" and not number.is_integer():
        raise ValueError(f"{field} must be an integer count")
    return number


def load_manifests(manifest_dir: Path) -> dict[str, dict]:
    manifests: dict[str, dict] = {}
    if not manifest_dir.exists():
        return manifests
    for path in sorted(manifest_dir.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"invalid manifest {path}: {exc}") from exc
        article_id = str(data.get("article_id") or "").strip()
        if article_id:
            manifests[article_id] = data
    return manifests


def load_metrics(metrics_csv: Path, known_article_ids: set[str]) -> list[dict]:
    with metrics_csv.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        headers = set(reader.fieldnames or [])
        missing = REQUIRED_COLUMNS - headers
        if missing:
            raise ValueError("missing required columns: " + ", ".join(sorted(missing)))
        suspicious = {
            h for h in headers
            if h and (h.lower() in FORBIDDEN_PII_HINTS or any(token in h.lower() for token in FORBIDDEN_PII_HINTS))
        }
        if suspicious:
            raise ValueError("PII-like columns are forbidden: " + ", ".join(sorted(suspicious)))
        unknown = headers - ALLOWED_METRIC_COLUMNS
        if unknown:
            raise ValueError("unsupported columns: " + ", ".join(sorted(unknown)))

        rows = []
        for line_no, row in enumerate(reader, start=2):
            article_id = (row.get("article_id") or "").strip()
            if not article_id:
                raise ValueError(f"line {line_no}: article_id is required")
            if article_id not in known_article_ids:
                raise ValueError(f"line {line_no}: unknown article_id {article_id}; refusing ambiguous attribution")
            parsed = {k: (row.get(k) or "").strip() for k in headers if k not in NUMERIC_COLUMNS}
            parsed["article_id"] = article_id
            method = parsed.get("attribution_method", "").lower()
            if method not in ATTRIBUTION_METHODS:
                raise ValueError(f"line {line_no}: attribution_method must be one of {sorted(ATTRIBUTION_METHODS)}")
            parsed["attribution_method"] = method
            for field in NUMERIC_COLUMNS:
                parsed[field] = _optional_number(row.get(field, ""), field) if field in headers else None
            disallowed_present = [
                field for field in NUMERIC_COLUMNS
                if parsed.get(field) is not None and field not in METHOD_ALLOWED_METRICS[method]
            ]
            if disallowed_present:
                raise ValueError(
                    f"line {line_no}: attribution_method={method} cannot support metrics: "
                    + ", ".join(sorted(disallowed_present))
                )
            rows.append(parsed)
    return rows


def _safe_rate(num, den):
    if num is None or den is None or den <= 0:
        return None
    return num / den


def build_rollup(manifests: dict[str, dict], rows: list[dict]) -> dict:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        grouped[row["article_id"]].append(row)

    articles = []
    for article_id, manifest in sorted(manifests.items()):
        article_rows = grouped.get(article_id, [])
        sums = {}
        coverage = {}
        for field in NUMERIC_COLUMNS:
            values = [r[field] for r in article_rows if r.get(field) is not None]
            sums[field] = sum(values) if values else None
            coverage[field] = len(values)
        articles.append({
            "article_id": article_id,
            "source": manifest.get("source"),
            "source_url": manifest.get("source_url"),
            "note_title": manifest.get("note_title"),
            "note_url": next((r.get("note_url") for r in reversed(article_rows) if r.get("note_url")), ""),
            "decision_score": manifest.get("decision_score"),
            "commercial_value_score": manifest.get("commercial_value_score"),
            "shelf_life": manifest.get("shelf_life"),
            "portfolio_topic": manifest.get("portfolio_topic"),
            "metrics": sums,
            "coverage_rows": coverage,
            "attribution_methods": sorted({r.get("attribution_method") for r in article_rows if r.get("attribution_method")}),
            "cta_click_rate": _safe_rate(sums["cta_clicks"], sums["note_views"]),
            "subscriber_conversion_per_click": _safe_rate(sums["new_subscribers"], sums["cta_clicks"]),
            "subscriber_conversion_per_view": _safe_rate(sums["new_subscribers"], sums["note_views"]),
            "subscription_revenue_per_1000_views_yen": (
                _safe_rate(sums["subscription_revenue_yen"], sums["note_views"]) * 1000
                if _safe_rate(sums["subscription_revenue_yen"], sums["note_views"]) is not None else None
            ),
        })

    totals = {}
    for field in NUMERIC_COLUMNS:
        vals = [a["metrics"][field] for a in articles if a["metrics"][field] is not None]
        totals[field] = sum(vals) if vals else None
    return {
        "schema_version": 1,
        "business_model": "free_note -> paid decision DB + monthly summary subscription",
        "privacy": "aggregate metrics only; subscriber PII forbidden",
        "ranking_feedback_enabled": False,
        "article_count": len(manifests),
        "measured_article_count": sum(1 for a in articles if any(v is not None for v in a["metrics"].values())),
        "totals": totals,
        "overall_cta_click_rate": _safe_rate(totals["cta_clicks"], totals["note_views"]),
        "overall_subscriber_conversion_per_click": _safe_rate(totals["new_subscribers"], totals["cta_clicks"]),
        "overall_subscriber_conversion_per_view": _safe_rate(totals["new_subscribers"], totals["note_views"]),
        "articles": articles,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Aggregate free-note to subscription metrics without subscriber PII")
    parser.add_argument("--metrics", required=True, type=Path, help="Aggregate metrics CSV")
    parser.add_argument("--manifest-dir", type=Path, default=Path("subscription_attribution/articles"))
    parser.add_argument("--output", type=Path, default=Path("subscription_attribution/metrics_rollup.json"))
    args = parser.parse_args()

    manifests = load_manifests(args.manifest_dir)
    if not manifests:
        raise SystemExit("No Ready-article attribution manifests found.")
    rows = load_metrics(args.metrics, set(manifests))
    rollup = build_rollup(manifests, rows)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(rollup, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({
        "articles": rollup["article_count"],
        "measured_articles": rollup["measured_article_count"],
        "output": str(args.output),
        "ranking_feedback_enabled": False,
    }, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
