from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"expected patch anchor not found: {path}: {old[:80]!r}")
    if text.count(old) != 1:
        raise SystemExit(f"patch anchor not unique: {path}: count={text.count(old)}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")


replace_once(
    "run180_eyecatch_semantic_layout.py",
    "- headline相当のtitle_linesは1〜3行。原則2〜3行を優先する。",
    "- headline相当のtitle_linesは1〜3行。2行を第一選択とし、2行では固有名詞・意味のまとまり・十分な文字サイズを守れない場合のみ3行を使う。必要な場合のみ3行とし、3行は正常なfallbackであり公開不可理由にしない。",
)

replace_once(
    "run181_eyecatch_visual_balance.py",
    "IMPACT_SUBTITLE_MIN_TOP = 510\nIMPACT_FOOTER_TOP = 625\nIMPACT_LEFT = 48\nIMPACT_TEXT_RIGHT = 808\n",
    "IMPACT_SUBTITLE_MIN_TOP = 510\nIMPACT_FOOTER_TOP = 625\nIMPACT_LEFT = 48\nIMPACT_TEXT_RIGHT = 808\n\n# Title-line publication policy: two lines are the visual ideal; three lines are a normal\n# fallback when preserving meaning/readability needs more vertical room. Three lines alone\n# must never block publication.\nIMPACT_TITLE_PREFERRED_LINES = 2\nIMPACT_TITLE_MAX_LINES = 3\nIMPACT_THREE_LINE_GAP_MAX = 10\nIMPACT_THREE_LINE_TITLE_TOP = 226\nIMPACT_THREE_LINE_SAFE_BOTTOM = 520\nIMPACT_THREE_LINE_SUBTITLE_MIN_TOP = 526\nIMPACT_THREE_LINE_TITLE_MAX_FONT = 80\nIMPACT_THREE_LINE_SUBTITLE_MAX_FONT = 24\n",
)

old_title_size = '''def _impact_title_size(lines: list[str], base_size: int, line_gap: int) -> int:\n    """Make the main copy as large as geometry allows, including vertical fit."""\n    try:\n        base = max(48, int(base_size))\n    except (TypeError, ValueError):\n        base = 60\n    target = min(IMPACT_TITLE_MAX_FONT, base + IMPACT_TITLE_FONT_BOOST)\n    probe = Image.new("RGB", (ee.WIDTH, ee.HEIGHT), (255, 255, 255))\n    draw = ImageDraw.Draw(probe)\n    for candidate in range(target, 47, -1):\n        font = ee._jp_font(candidate, bold=True)\n        widths = [ee._text_width(draw, line, font) for line in lines]\n        heights = [_run_bbox_height(draw, line, font) for line in lines]\n        block_height = sum(heights) + max(0, len(lines) - 1) * int(line_gap)\n        if all(width <= TITLE_MAX_WIDTH for width in widths) and IMPACT_TITLE_TOP + block_height <= IMPACT_TITLE_SAFE_BOTTOM:\n            return candidate\n    return min(base, IMPACT_TITLE_MAX_FONT)\n\n\n'''
new_title_size = '''def _impact_layout_profile(lines: list[str], requested_gap: int) -> dict[str, int | bool]:\n    """Return deterministic geometry for the preferred 2-line or normal 3-line title."""\n    line_count = max(1, min(len(lines) or 1, IMPACT_TITLE_MAX_LINES))\n    try:\n        gap = int(requested_gap)\n    except (TypeError, ValueError):\n        gap = 12\n    gap = max(8, min(18, gap))\n    if line_count >= 3:\n        return {\n            "line_count": 3,\n            "is_three_line": True,\n            "title_top": IMPACT_THREE_LINE_TITLE_TOP,\n            "title_safe_bottom": IMPACT_THREE_LINE_SAFE_BOTTOM,\n            "title_max_font": IMPACT_THREE_LINE_TITLE_MAX_FONT,\n            "line_gap": min(gap, IMPACT_THREE_LINE_GAP_MAX),\n            "subtitle_min_top": IMPACT_THREE_LINE_SUBTITLE_MIN_TOP,\n            "subtitle_max_font": IMPACT_THREE_LINE_SUBTITLE_MAX_FONT,\n        }\n    return {\n        "line_count": line_count,\n        "is_three_line": False,\n        "title_top": IMPACT_TITLE_TOP,\n        "title_safe_bottom": IMPACT_TITLE_SAFE_BOTTOM,\n        "title_max_font": IMPACT_TITLE_MAX_FONT,\n        "line_gap": gap,\n        "subtitle_min_top": IMPACT_SUBTITLE_MIN_TOP,\n        "subtitle_max_font": 29,\n    }\n\n\ndef _impact_title_size(lines: list[str], base_size: int, line_gap: int) -> int:\n    """Make main copy as large as its 2-line/3-line geometry safely allows."""\n    try:\n        base = max(48, int(base_size))\n    except (TypeError, ValueError):\n        base = 60\n    profile = _impact_layout_profile(lines, line_gap)\n    target = min(int(profile["title_max_font"]), base + IMPACT_TITLE_FONT_BOOST)\n    effective_gap = int(profile["line_gap"])\n    probe = Image.new("RGB", (ee.WIDTH, ee.HEIGHT), (255, 255, 255))\n    draw = ImageDraw.Draw(probe)\n    for candidate in range(target, 47, -1):\n        font = ee._jp_font(candidate, bold=True)\n        widths = [ee._text_width(draw, line, font) for line in lines]\n        heights = [_run_bbox_height(draw, line, font) for line in lines]\n        block_height = sum(heights) + max(0, len(lines) - 1) * effective_gap\n        if (\n            all(width <= TITLE_MAX_WIDTH for width in widths)\n            and int(profile["title_top"]) + block_height <= int(profile["title_safe_bottom"])\n        ):\n            return candidate\n    # Preserve publication yield for already-validated legacy plans. Run180 geometry normally\n    # guarantees a fit; this compatibility return avoids turning line count into a hard block.\n    return min(base, int(profile["title_max_font"]))\n\n\n'''
replace_once("run181_eyecatch_visual_balance.py", old_title_size, new_title_size)

old_highlight = '''def _fit_impact_highlight_size(\n    lines: list[str], normal_size: int, line_gap: int, highlight_text: str | None\n) -> int:\n    if not highlight_text or HIGHLIGHT_FONT_SCALE <= 1.0:\n        return int(normal_size)\n    base = int(normal_size)\n    target = min(IMPACT_HIGHLIGHT_MAX_FONT, max(base, int(round(base * HIGHLIGHT_FONT_SCALE))))\n    probe = Image.new("RGB", (ee.WIDTH, ee.HEIGHT), (255, 255, 255))\n    draw = ImageDraw.Draw(probe)\n    normal_font = ee._jp_font(base, bold=True)\n    all_runs = [_split_line_for_highlight(lines, i, highlight_text) for i in range(len(lines))]\n    for candidate in range(target, base - 1, -1):\n        highlight_font = ee._jp_font(candidate, bold=True)\n        heights: list[int] = []\n        fits = True\n        for runs in all_runs:\n            width, height = _mixed_line_metrics(draw, runs, normal_font, highlight_font)\n            if width > TITLE_MAX_WIDTH:\n                fits = False\n                break\n            heights.append(height)\n        if not fits:\n            continue\n        block_height = sum(heights) + max(0, len(heights) - 1) * int(line_gap)\n        if IMPACT_TITLE_TOP + block_height <= IMPACT_TITLE_SAFE_BOTTOM:\n            return candidate\n    return base\n\n\n'''
new_highlight = '''def _fit_impact_highlight_size(\n    lines: list[str], normal_size: int, line_gap: int, highlight_text: str | None\n) -> int:\n    if not highlight_text or HIGHLIGHT_FONT_SCALE <= 1.0:\n        return int(normal_size)\n    base = int(normal_size)\n    profile = _impact_layout_profile(lines, line_gap)\n    max_highlight = min(IMPACT_HIGHLIGHT_MAX_FONT, int(profile["title_max_font"]) + 16)\n    target = min(max_highlight, max(base, int(round(base * HIGHLIGHT_FONT_SCALE))))\n    effective_gap = int(profile["line_gap"])\n    probe = Image.new("RGB", (ee.WIDTH, ee.HEIGHT), (255, 255, 255))\n    draw = ImageDraw.Draw(probe)\n    normal_font = ee._jp_font(base, bold=True)\n    all_runs = [_split_line_for_highlight(lines, i, highlight_text) for i in range(len(lines))]\n    for candidate in range(target, base - 1, -1):\n        highlight_font = ee._jp_font(candidate, bold=True)\n        heights: list[int] = []\n        fits = True\n        for runs in all_runs:\n            width, height = _mixed_line_metrics(draw, runs, normal_font, highlight_font)\n            if width > TITLE_MAX_WIDTH:\n                fits = False\n                break\n            heights.append(height)\n        if not fits:\n            continue\n        block_height = sum(heights) + max(0, len(heights) - 1) * effective_gap\n        if int(profile["title_top"]) + block_height <= int(profile["title_safe_bottom"]):\n            return candidate\n    return base\n\n\n'''
replace_once("run181_eyecatch_visual_balance.py", old_highlight, new_highlight)

old_render = '''    line_gap = max(8, min(18, int(validated.get("title_line_gap", 12))))\n    title_size = _impact_title_size(title_lines, int(validated.get("title_font_size", 60)), line_gap)\n    normal_font = ee._jp_font(title_size, bold=True)\n    highlight_size = _fit_impact_highlight_size(title_lines, title_size, line_gap, highlight_text)\n    highlight_font = ee._jp_font(highlight_size, bold=True)\n\n    y = IMPACT_TITLE_TOP\n'''
new_render = '''    requested_gap = max(8, min(18, int(validated.get("title_line_gap", 12))))\n    profile = _impact_layout_profile(title_lines, requested_gap)\n    line_gap = int(profile["line_gap"])\n    title_size = _impact_title_size(title_lines, int(validated.get("title_font_size", 60)), line_gap)\n    normal_font = ee._jp_font(title_size, bold=True)\n    highlight_size = _fit_impact_highlight_size(title_lines, title_size, line_gap, highlight_text)\n    highlight_font = ee._jp_font(highlight_size, bold=True)\n\n    y = int(profile["title_top"])\n'''
replace_once("run181_eyecatch_visual_balance.py", old_render, new_render)

old_sub = '''    sub_lines, sub_size = _subheadline_lines(draw, title, summary, validated)\n    sub_top = max(IMPACT_SUBTITLE_MIN_TOP, title_bottom + 18)\n    sub_font = ee._jp_font(sub_size, bold=True)\n    sub_step = max(34, sub_size + 10)\n'''
new_sub = '''    sub_lines, sub_size = _subheadline_lines(draw, title, summary, validated)\n    is_three_line = bool(profile["is_three_line"])\n    sub_size = min(sub_size, int(profile["subtitle_max_font"]))\n    sub_top = max(\n        int(profile["subtitle_min_top"]),\n        title_bottom + (14 if is_three_line else 18),\n    )\n    sub_font = ee._jp_font(sub_size, bold=True)\n    sub_step = max(32 if is_three_line else 34, sub_size + (8 if is_three_line else 10))\n'''
replace_once("run181_eyecatch_visual_balance.py", old_sub, new_sub)

# Reference documentation: append an explicit publication-yield contract without rewriting history.
ref = Path("docs/reference/RUN181_EYECATCH_IMPACT_HIERARCHY.md")
ref_text = ref.read_text(encoding="utf-8")
marker = "## Title line publication policy (2026-09-06)"
if marker not in ref_text:
    ref_text += '''\n\n## Title line publication policy (2026-09-06)\n\n- Main title is **2 lines preferred**, not 2 lines mandatory.\n- **3 lines are a normal fallback** when two lines would damage semantic grouping, protected product/model names, or readable type size.\n- A three-line title alone is never a publication-blocking condition.\n- Three-line mode uses a compact deterministic profile: slightly smaller maximum title size, tighter line gap, modestly earlier title top, extra safe-bottom room, and a capped subheadline size.\n- Right-side illustration/background, orange emphasis, font contract and footer remain unchanged.\n- No additional Gemini/provider/image-generation request is introduced.\n'''
    ref.write_text(ref_text, encoding="utf-8")

spec = Path("AI_Intelligence_Factory_最終仕様書.md")
spec_text = spec.read_text(encoding="utf-8")
spec_marker = "### Run181 title-line publication policy (2026-09-06)"
if spec_marker not in spec_text:
    spec_text += '''\n\n### Run181 title-line publication policy (2026-09-06)\n\nEyecatch main-title line count is a yield-aware presentation contract: **2 lines are preferred; up to 3 lines are valid production output**. Three lines are used when preserving semantic chunks, protected product/model names, or readable typography needs extra vertical room. Three-line mode is not a reason to withhold an otherwise publishable article. Run181 applies a compact three-line geometry profile while retaining the approved right-side illustration/background, Noto Sans JP / Inter font contract, restrained #F28C28 emphasis, and zero additional provider/image-generation calls.\n'''
    spec.write_text(spec_text, encoding="utf-8")

print("Run181 two-line preferred / three-line fallback policy applied")
